config/routes.rb
Rails.application.routes.draw do
  post '/notes', to: 'notes#update'
  get '/notes', to: 'notes#index'

  resources :users, only: [:new, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root to: redirect('/index.html')
  get '/sample_login', to: 'sessions#sample_new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :diaries
  validates :name, length: 2..20, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    if @current_user_memo
      @current_user_memo
    elsif session[:user_id]
      user = User.find_by(id: session[:user_id])
      @current_user_memo = user
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        session[:user_id] ||= user.id
        @current_user_memo = user
      else
        nil
      end
    else
      nil
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :check_login

  def index
    @current_user = current_user
    if params[:dates_from].blank? || params[:dates_to].blank?
      @date = Date.today
      @note = @current_user.notes.find_or_initialize_by(date: @date)
      render :show
    else
      @dates_from = Date.parse(params[:dates_from])
      @dates_to   = Date.parse(params[:dates_to])
      @notes = (@dates_from..@dates_to).map do |date|
        @current_user.notes.find_or_initialize_by(date: date)
      end
    end
  end

  def update
    date = params[:note][:date]
    text = CGI.unescape_html(params[:note][:text])
    note = current_user.notes.find_or_initialize_by(date: date)
    if text.blank?
      note.delete
    else
      note.update(text: text, date: date)
    end
  end

  private

  def check_login
    if current_user.nil?
      redirect_to root_path
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :check_login

  def show
    @current_user = current_user
    @date         = Date.parse(params[:id])
    @note         = @current_user.notes.find_or_initialize_by(date: @date)
  end

  def index
    @current_user = current_user
    if params[:dates_from].blank? || params[:dates_to].blank?
      @date = Date.today
      @note = @current_user.notes.find_or_initialize_by(date: @date)
      render :show
    else
      @dates_from = Date.parse(params[:dates_from])
      @dates_to   = Date.parse(params[:dates_to])
      @notes = (@dates_from..@dates_to).map do |date|
        @current_user.notes.find_or_initialize_by(date: date)
      end
    end
  end

  def update
    date = params[:note][:date]
    text = CGI.unescape_html(params[:note][:text])
    note = current_user.notes.find_or_initialize_by(date: date)
    if text.blank?
      note.delete
    else
      note.update(text: text, date: date)
    end
  end

  def csv_download
    year = params[:year].to_i
    date_range = Date.new(year, 1, 1)..Date.new(year, 12, 31)
    bom = "\uFEFF"
    csv_data = bom + CSV.generate(headers: %w[date text], write_headers: true, force_quotes: true) do |csv|
      current_user.notes.where(date: date_range).order(:date).each do |note|
        csv << [
          note.date,
          note.text
        ]
      end
    end
    send_data csv_data, type: 'text/csv; charset=utf8', filename: "notes_#{year}.csv"
  end

  private

  def check_login
    if current_user.nil?
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def sample_new
    user = User.find_by(name: 'sample_user') || User.create(name: 'sample_user', password: '0000')
    session[:user_id] = user.id
    redirect_to notes_path
  end

  def create # ログイン
    @name = params[:session][:name]
    user = User.find_by(name: @name)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      if params[:session][:remember_me] == '1'
        remember_token  = SecureRandom.urlsafe_base64
        remember_digest = BCrypt::Password.create(remember_token, cost: BCrypt::Engine::MIN_COST)
        user.update(remember_digest: remember_digest)
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = remember_token
      else
        user.update(remember_digest: nil)
        cookies.delete(:remember_token)
      end
      redirect_to notes_path
    else
      flash.now[:danger] = '名前かパスワードが間違えています'
      render 'new'
    end
  end

  def destroy # ログアウト
    if user = current_user
      user.update_attribute(:remember_digest, nil)
      session.delete(:user_id)
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to notes_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/highlight.js/latest/highlight.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/highlight.js/latest/styles/github.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_day_menu.html.erb
<ul class='day_menu'>
  <%
    target_dates = Array(target_dates)
    dates = case target_dates.first.beginning_of_month.wday
            when 0
              [*1..6].reverse.map { |i| target_dates.first.beginning_of_month - i }
            else
              [*1..(target_dates.first.beginning_of_month.wday - 1)].reverse.map { |i| target_dates.first.beginning_of_month - i }
            end
    dates += [*target_dates.first.beginning_of_month..target_dates.first.end_of_month]
    unless (dates.size % 7).zero?
      dates += [*1..(7 - dates.size % 7)].map { |i| target_dates.first.end_of_month + i }
    end
  %>
  <% dates.each_slice(7).each do |week_dates| %>
    <br>
    <li class='weeks-link'>
      <%= link_to((week_dates.compact.first.strftime('%W').to_i + 1).to_s + '週', notes_path(dates_from: week_dates.compact.first, dates_to: week_dates.compact.last)) %>
    </li>
    <% week_dates.each do |date| %>
      <% if date %>
        <% wd_class = %w[sun mon tue wed thu fri sat][date.wday] %>
        <li class="<%= date.in?(target_dates) ? 'current_day' : '' %> <%= date.month == target_dates.first.month ? 'current_month' : ''%>">
          <%= link_to("#{date.day}日", note_path(Date.new(date.year, date.month, date.day)), { class: wd_class }) %>
        </li>
      <% else %>
        <li>-</li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/notes/_footer.html.erb
<div class="footer">
  <hr>
  <div class='csvdl'><%= link_to('CSVをダウンロード', csv_download_path(format: 'csv', year: date.year)) %></div>
  <div class='logout'><%= link_to('ログアウト', logout_path)%></div>
</div>

app/views/notes/_header.html.erb
<div class="header">
  <h1 class="title"><%= link_to("#{@current_user.name}の日記", notes_path) %></h1>
</div>

app/views/notes/_month_menu.html.erb
<ul class='month_menu'>
  <li><%= link_to("#{date.year - 1}年", note_path(Date.new(date.year - 1, 12, 31))) %></li>
  <% (1..12).each do |m|%>
    <li class="<%= m == date.month ? 'current_month' : '' %>">
      <%= link_to("#{m == date.month ? "#{date.year}年" : '' }#{m}月", notes_path(dates_from: Date.new(date.year, m, 1), dates_to: Date.new(date.year, m, 1).end_of_month)) %>
    </li>
  <% end %>
  <li><%= link_to("#{date.year + 1}年", note_path(Date.new(date.year + 1, 1, 1))) %></li>
</ul>

app/views/notes/_note.html.erb
<div class="note" note-date="<%= note.date %>" >
  <div hidden class='init-value'><%= note.text %></div>
  <% wd = %w[日 月 火 水 木 金 土][note.date.wday] %>
  <% wd_class = %w[sun mon tue wed thu fri sat][note.date.wday] %>
  <h2>
    <%= link_to(note_path(note)) do %>
      <%= "#{note.date.month}/#{note.date.day}" %><span class='<%= wd_class %>'>(<%= wd %>)</span>
    <% end %>
  </h2>
  <textarea class="md-editor"></textarea>
  <button class='copy'>copy</button>
  <p class='last-modified'>-</p>
</div>

app/views/notes/index.html.erb
<%= render('header') %>

<% @notes.each do |note| %>
  <%= render('note', {note: note}) %>
<% end %>

<div class='menu'>
  <%= render('day_menu', {target_dates: @dates_from..@dates_to}) %>
  <%= render('month_menu', {date: @dates_from}) %>
</div>

<%= render('footer', {date: @dates_from}) %>

<%= stylesheet_link_tag params[:controller] %>

app/views/notes/show.html.erb
<%= render('header') %>

<%= render('note', {note: @note}) %>

<div class='menu'>
  <%= render('day_menu', {target_dates: @date}) %>
  <%= render('month_menu', {date: @date}) %>
</div>

<%= render('footer', {date: @date}) %>

<%= stylesheet_link_tag params[:controller] %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, value: @name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class='title'>新規登録</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', root_path %>

<%= stylesheet_link_tag params[:controller] %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>